### ISSUE TITLE
急！！！快点兼容DataBinding ，并且Fragment 也兼容Databinding

### ISSUE THREAD

**Issue by chenenqiang12345** [MeetYouDevs/Android-Skin#10]
急！！！快点兼容DataBinding ，并且Fragment 也兼容Databinding！！！！
老板 需要多久？？？？？

**Comment by iceAnson** [comment]
databinding的原理是最后代码直接调用了中间代码来设置资源的方法，比如TextView.setTextColor(R.color.red);目前还没有找到可以拦截的地方。
