### ISSUE TITLE
Fragment中使用AndroidSkin.getLayoutInflater后自定义字体不生效

### ISSUE THREAD

**Issue by XanderShen** [MeetYouDevs/Android-Skin#12]
Android O中新引入了Fonts in XML的特性，如链接所示：https://developer.android.com/guide/topics/ui/look-and-feel/fonts-in-xml.html
Fragment中使用AndroidSkin.getLayoutInflater后利用该特性设置的自定义字体不生效

**Comment by iceAnson** [comment]
代码已提交，下个版本发布
