### ISSUE TITLE
找不到 setFactory2()

### ISSUE THREAD

**Issue by 1196278096** [MeetYouDevs/Android-Skin#8]
\Android-Skin-master\skinlib\src\main\java\com\meiyou\skinlib\AndroidSkinHook.java:73: 错误: 找不到符号
            LayoutInflaterCompat.setFactory2(layoutInflater, AndroidSkinFactory.from(context,layoutInflater));
                                ^
  符号:   方法 setFactory2(LayoutInflater,AndroidSkinFactory)
  位置: 类 LayoutInflaterCompat
注: 某些输入文件使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
注: 某些输入文件使用了未经检查或不安全的操作。
注: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。
1 个错误

 FAILED

FAILURE: Build failed with an exception.

**Comment by iceAnson** [comment]
请确认一下LayoutInflaterCompat这个类是否是26.1.0版本的；

**Comment by 1196278096** [comment]
这个库使用一定要sdk是26+的版本吗？

**Comment by iceAnson** [comment]
不是，但是要使用低版本得按照评论第一条修改代码

**Comment by iceAnson** [comment]
是你之前的说的另外一个issue
