### ISSUE TITLE
Fragment布局文件中使用的资源换肤无效

### ISSUE THREAD

**Issue by 1196278096** [MeetYouDevs/Android-Skin#9]
主界面中有四个Fragment，Fragment布局文件中的资源换肤无效

**Comment by iceAnson** [comment]
onCreateView里的LayoutInflater要使用AndroidSkin.getLayoutInflater

**Comment by iceAnson** [comment]
1.0.9版本

**Comment by 1196278096** [comment]
改成1.0.8和1.0.9都是编译不通过，Failed to resolve: com.meiyou:android-skin:1.0.9

**Comment by iceAnson** [comment]
1.0.9现在可以了

**Comment by 1196278096** [comment]
谢谢，还有个问题请教一下，recyclerview和listview换肤后，列表刷新item的皮肤就会错乱，然后会变成默认主题，请问一下这个应该怎么改？

**Comment by iceAnson** [comment]
这个和Android-Skin有关系吗，你是手动调用的某个View的换肤？

**Comment by 1196278096** [comment]
没有 就是普通的recyclerview加载列表，我现在处理方法是onCreatView中判断是否有换肤，如果有换肤就把图标、字体颜色、背景等都换掉 然后就好了

**Comment by iceAnson** [comment]
额，那岂不是手动设置，onCreateView设置AndroidSkin.getLayoutInflater来layout资源不行吗

**Comment by 1196278096** [comment]
用AndroidSkin.getLayoutInflater也不行，这个问题应该比较好复现，列表有添加记录，或者有dialog弹出界面，返回刷新时就会出现。还有xml中listview的divider分割线也不能换肤，且动态设置也不行。

**Comment by iceAnson** [comment]
https://github.com/iceAnson/Android-Skin
这里有recycleview换肤的demo
